### ISSUE TITLE
Using python3.9 and xlsxgrep results in errors

### ISSUE THREAD

**Issue by drhey** [zazuum/xlsxgrep#8] opened 2021-04-06 14:03 UTC
With python3.9 and `xlsxgrep` installed via `pip3`, previously known behavior like:

```
xlsxgrep -i <pattern> *.xlsx
```

results in:

```
Error:    Unsupported format, password protected or corrupted file:
```

I suspect that python3.9 might be the issue, because reverting to python3.8 and installing `xlsxgrep` in the same manner works as expected. I confirmed this in a python `virtualenv`.

**Comment by Samyak2** [comment] 2021-10-06 16:24
A similar issue was raised in #3 

I got it working with python 3.9.7 using [this](https://github.com/zazuum/xlsxgrep/issues/3#issuecomment-936604437)

**Comment by zazuum** [comment] 2021-10-12 10:25
The issue is resolved with latest upgraded lib dependencies.
For already installed package issue can be fixed with library upgrade:  
pip3 install -U --upgrade-strategy eager xlsxgrep

**Closed as completed by zazuum** 2021-10-12 10:25 UTC
