### ISSUE TITLE
Unsupported format, password protected or corrupted file

### ISSUE THREAD

**Issue by joelnitta** [zazuum/xlsxgrep#3] opened 2020-12-12 21:24 UTC
This looks like a fantastic tool for hunting down poorly named/organized excel files (I task I wish I didn't have to do so often)!

I am frequently encountering `Error:    Unsupported format, password protected or corrupted file`, even when the file is not password protected and opens in Excel with no problem.

Here is an example file: https://www.dropbox.com/s/5wtpuhxjzbkfxr7/table.xlsx?dl=0

xlsxgrep  0.0.24, Python 3.8.3, running on a mac 10.15.7

Thanks!

**Comment by zazuum** [comment] 2020-12-14 12:02
Bug confirmed. Issue is with updated xlrd library that dropped support for xlsx files due to security reasons.Temporary possible workaround would be installing downgraded xlrd library via pip.

**Comment by joelnitta** [comment] 2020-12-14 22:22
Thanks for the prompt answer! I was able to get it working in a venv with xlrd==1.2.0

**Comment by Samyak2** [comment] 2021-10-06 16:22
I had to use `1.1.0` to work with some xlsx files.
```
pip install xlrd==1.1.0
```

---

Have you considered some alternatives for `xlrd`? This website lists some of them: http://www.python-excel.org/

[pylightxl](https://github.com/PydPiper/pylightxl) in particular seems promising.

**Comment by zazuum** [comment] 2021-10-12 10:26
The issue is resolved with latest upgraded lib dependencies so there's no need for running downgraded xlrd.
Pylightxl doesn't support  .xls and .ods files so I wouldn't consider it for now.

For already installed package issue can be fixed with library upgrade:  
pip3 install -U --upgrade-strategy eager xlsxgrep

**Closed as completed by zazuum** 2021-10-12 10:26 UTC
Labels: bug
